PITB.CMS/Controllers/View/AdminStakeholderController.cs
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Linq;
using System.Text;
using System.Web.Mvc;
using Newtonsoft.Json;
using System.Data;
using PITB.CMS_Common.Models.View;
using PITB.CMS_Common.Handler.Business;
using PITB.CMS_Common.Models;
using PITB.CMS_Common.Handler.DataTableJquery;
using PITB.CMS_Common.Models.Custom.DataTable;
using PITB.CMS_Common.Helper;
using PITB.CMS_Common.Handler.Authorization;
using PITB.CMS_Common.Handler.Authentication;

namespace PITB.CMS.Controllers.View
{
    [AuthorizePermission]
    public class AdminStakeholderController : Controller
    {
        // GET: AdminStakeholder
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult AddEditUser()
        {
            VmAddStakeholderUser vms = BIStakeholderAdmin.GetVmAddStakeholderUser();
            
            return View("~/Views/AdminStakeholder/AddEditUser.cshtml", AuthenticationHandler.GetCookie().MasterPage, vms);
        }
        public ActionResult AddCampaignTag()
        {
            VmAddStakeholderUser vms = BIStakeholderAdmin.GetVmAddCampaigns();
            ViewBag.TagsList = "asad,javed";
            return View("~/Views/AdminStakeholder/AddCampaignTag.cshtml", AuthenticationHandler.GetCookie().MasterPage, vms);
        }

        [System.Web.Mvc.HttpPost]
        public ActionResult OnAddUserSubmit(VmAddStakeholderUser vms)
        {
            ResponseData response = new ResponseData();
            
            if (ModelState.IsValid)
            {
                bool isduplicate = BIStakeholderAdmin.IsUserPresentWithUsername(vms.UserName);
                if (isduplicate)
                {
                    response.messageText = "Username already exists.";
                    response.css_cls = "error";
                    response.messageTitle = "Error";
                    response.statusId = 2;
                }
                else
                {
                    bool user = BIStakeholderAdmin.AddUser(vms);
                    if (user == false)
                    {
                        response.messageText = "User data is invalid.";
                        response.css_cls = "error";
                        response.messageTitle = "Error";
                        response.statusId = 2;
                    }
                    else
                    {
                        response.messageText = "User successfully added.";
                        response.css_cls = "success";
                        response.messageTitle = "Success";
                        response.statusId = 1;
                    }
                }
            }
                
               
            return Json(response);
        }
        [System.Web.Mvc.HttpPost]
        public ActionResult OnEditUserSubmit(VmEditStakeholderUser vms)
        {
            ResponseData response = new ResponseData();
            if (ModelState.IsValid)
            {
                var user = BIStakeholderAdmin.EditUserSubmit(vms);
                if (user != null)
                {
                    response.messageText = "User successfully edited.";
                    response.css_cls = "success";
                    response.messageTitle = "Success";
                    response.statusId = 1;
                }
            }
            else
            {
                response.messageText = "Error in saving data.";
                response.css_cls = "error";
                response.messageTitle = "Error";
                response.statusId = 2;
            }
           
            return Json(response);
        }

        [System.Web.Mvc.HttpPost]
        public ActionResult AddUser()
        {
            VmAddStakeholderUser vms = BIStakeholderAdmin.GetAddUser();

            return PartialView("~/Views/AdminStakeholder/_AddForm.cshtml", vms);
        }

        [System.Web.Mvc.HttpPost]
        public ActionResult EditUser(int UserID)
        {
            VmEditStakeholderUser vms = BIStakeholderAdmin.GetEditUser(UserID);

            return PartialView("~/Views/AdminStakeholder/_EditUserForm.cshtml", vms);
        }
        [System.Web.Mvc.HttpGet]
        public JsonResult GetProvinceList(int campaignId)
        {
            List<SelectListItem> selectLists = DbProvince.AllProvincesList().Select(x=> new SelectListItem(){Text = x.Province_Name,Value=x.Province_Id.ToString() }).ToList();
            //selectLists.Insert(0, new SelectListItem { Text = "--Select--", Value = (-1).ToString() });
            return Json(selectLists, JsonRequestBehavior.AllowGet);
        }
        [System.Web.Mvc.HttpGet]
        public ActionResult GetDivisionList(int provinceId, int campaignId)
        {
            IEnumerable<SelectListItem> SelectList = DbDivision.GetSelectListofDivisionForCampaignAndProvinceIds(campaignId, provinceId);
            return Json(SelectList, JsonRequestBehavior.AllowGet);
        }
        [System.Web.Mvc.HttpGet]
        public ActionResult GetDistrictList(int divisionId, int campaignId)
        {
            IEnumerable<SelectListItem> SelectList = DbDistrict.GetSelectListofDistrictForCampaignAndDivisionIds(campaignId, divisionId);
            return Json(SelectList, JsonRequestBehavior.AllowGet);
        }
        [System.Web.Mvc.HttpGet]
        public ActionResult GetTehsilList(int districtId, int campaignId)
        {
            IEnumerable<SelectListItem> SelectList = DbTehsil.GetSelectListofTehsilForCampaignAndDistrictIds(campaignId, districtId);
            return Json(SelectList, JsonRequestBehavior.AllowGet);
        }
        [System.Web.Mvc.HttpGet]
        public ActionResult GetUnionCouncilList(string tehsilId, int campaignId)
        {
            IEnumerable<SelectListItem> SelectList = DbUnionCouncils.GetSelectListofUnionCouncilForCampaignAndTehsilIds(campaignId, tehsilId);
            return Json(SelectList, JsonRequestBehavior.AllowGet);
        }
        [System.Web.Mvc.HttpGet]
        public ActionResult GetWardList(int unioncouncilId, int campaignId)
        {
            IEnumerable<SelectListItem> SelectList = DbWards.GetSelectListofWardForCampaignAndUnionCouncilIds(campaignId, unioncouncilId);
            return Json(SelectList, JsonRequestBehavior.AllowGet);
        }
        private struct ResponseData
        {
            public int statusId;
            public string messageText;
            public string css_cls;
            public string messageTitle;
            public ResponseData(int id,string text,string title,string css)
            {
                statusId = id;
                messageText = text;
                messageTitle = title;
                css_cls = css;
            }
        }

        public ActionResult BlockUser()
        {
            //VmAddStakeholderUser vms = BIStakeholderAdmin.GetVmAddStakeholderUser();

            return View("~/Views/AdminStakeholder/BlockUser.cshtml", BlView.Instance.GetMasterPageFromCookie() /*BlView.Instance.SetMasterPageInCookie("~/Views/Shared/_AdminStakeholderLayout.cshtml")*/);
        }


        [System.Web.Mvc.HttpPost]
        [ValidateInput(false)]
        public FileResult ExportTable(string GridHtml)
        {
            return File(Encoding.ASCII.GetBytes(GridHtml), "application/vnd.ms-excel", "Grid.xls");
        }




        [System.Web.Mvc.HttpPost]
        public string GetBlockList()
        {
            NameValueCollection formCollection = Request.Form;
            //string aoData2 = formCollection["aoData"];
            string aoData = Request["aoData"];

            DataTableParamsModel dtModel = DataTableHandler.ConvertaoDataToModel(aoData);
            DataTable dt= BIStakeholderAdmin.GetUserListings(dtModel);
            List<dynamic> listDynamic = dt.ToDynamic();
            int totalRecords=0, filteredRecords=0;
            if (listDynamic != null && listDynamic.Count > 0)
            {
                totalRecords = listDynamic[0].Total_Rows;
                filteredRecords = totalRecords;
            }
           
            //string str = JsonConvert.SerializeObject(listDynamic);
            //return Json(dt, JsonRequestBehavior.AllowGet);
            try
            {
                var jr = new 
                {
                    Data = new
                    {
                        aaData = listDynamic,
                        draw = dtModel.Draw,
                        recordsTotal = totalRecords,//dtModel.Length,
                        recordsFiltered = totalRecords, //dtModel.Length < rows ? dtModel.Length : rows//dtModel.Length
                    },
                    JsonRequestBehavior = JsonRequestBehavior.AllowGet
                };
                return JsonConvert.SerializeObject(jr);
            }
            catch (Exception ex)
            {

            }
            

            return null;
        }

        [System.Web.Mvc.HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SetUserActiveState(int userId, int isActive)
        {
            ResponseData rsp = new ResponseData();

            try
            {
                BIStakeholderAdmin.UpdatePersonActiveInactive(userId, isActive);
                rsp.statusId = 1;
                rsp.css_cls = "success";
                rsp.messageText = "User has " + (isActive == 1 ? "deactivated" : "activated") + " Successfully";
            }
            catch (Exception ex)
            {
                rsp.statusId = -1;
                rsp.css_cls = "error";
                rsp.messageText = "Exception =>" + ex.Message;
            }


            return Json(rsp, JsonRequestBehavior.AllowGet);
        }
    }
}

PITB.CMS/Views/AdminStakeholder/AddCampaignTag.cshtml
@using PITB.CMS_Common.Helper.Extensions;
@model VmAddStakeholderUser

@{
    ViewBag.Title = "AddEditUser";
    //Layout = "~/Views/Shared/_AdminStakeholderLayout.cshtml";
}
<style>
    .search-input-text {
        width: 100%;
    }

    .bootstrap-tagsinput {
        min-height: 150px;
        height: auto;
        width: auto;
    }

    .inputTags-list {
        height: 300px;
        margin-bottom: 20px;
    }

    .alert {
        display: none;
    }

    #inputTags {
        width: 100%;
        height: auto;
    }
</style>
<link href="~/css/tagsinput.css" rel="stylesheet" />




<div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12">
        <div class="box box-primary" style="padding: 0 30px;">
            <div class="box-header-blue with-border btn-header">
                <h4 class="box-title">Add Tags by Campaign</h4>
            </div>
            <br />
            <div class="row ">
                <div class="col-lg-3 col-md-3 col-sm-12">
                    <label>Campaigns</label>
                    @Html.DropDownListFor(m => m.Campaign, Model.CampaignSelectList, "--Select Campaign--", new { @Id = "GridControlCampaign", @class = "form-control" })
                </div>
                <div class="clearfix"></div>
                <br />
                <div class="col-lg-6 col-md-6 col-sm-12">
                    <label>Campaign Tags</label>
                    <input type="text" class="form-control" data-role="tagsinput" value="" id="inputTags" />
                </div>
                <div class="clearfix"></div>
                <br />
                <div class="col-lg-6 col-md-6 col-sm-12">
                    <button type="button" id="btnSave" class="btn btn-success" style="float:right;">Save</button>
                </div>
                <div class="clearfix"></div>
                <br />
            </div>
        </div>
    </div>
</div>


<script src="~/js/tagsinput.js"></script>
<script>
    $(function () {

        $("#GridControlCampaign").change(function () {
            if ($(this).val() != "") {
                $.ajax({
                    type: "GET",
                    url: '@Url.Action("GetTagsbyCampaign", "GeneralApi")',
                    data: { campaignId: $(this).val() },
                    //beforeSend: function () { $.showprogress(); },
                    success: function (msg) {
                        
                        $('#inputTags').tagsinput('removeAll');
                        $.each(msg, function (index, value) {
                            $('#inputTags').tagsinput('add', value);
                        });
                    }
                });
            }
            else {
                $('#inputTags').tagsinput('removeAll');
            }
        });

        $("#btnSave").click(function () {
            if ($("#GridControlCampaign").val() != "") {
                var psData = {};
                psData.TagsbyCampaign = $('#inputTags').val();
                psData.campaignId = $("#GridControlCampaign").val();
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": '@Url.Action("UpdateTagsbyCampaign", "GeneralApi")',
                    "data": psData,
                    "success": function (msg) {
                        if (msg == "success") {
                            toastr.success('Tags has been updated successfully.');
                        }
                        else {
                            toastr.error('Something went wrong please try again later.');
                        }
                    },
                });
            }
        });
    })

</script>

PITB.CMS/Views/AdminStakeholder/BlockUser.cshtml
@{
    ViewBag.Title = "BlockUser";
    //Layout = "~/Views/Shared/_AdminStakeholderLayout.cshtml";
}

@Html.AntiForgeryToken();
<h2>Block User</h2>
<div id="Loading" style="display:none;" class="LoadingBlock"></div>
@using (Html.BeginForm("ExportTable", "AdminStakeholder", FormMethod.Post))
{
    <input type="hidden" name="GridHtml" />
    <input type="submit" id="btnSubmit" value="Export" />
}
<div id ="Grid" class="box-body-white">
 
    <table id="agentListing" width="100%" class="table table-condensed table-hover table-bordered table-striped  responsive" role="grid" aria-describedby="agentListing">
        <thead>
            <tr role="row" class="tableHeader">
                <th>Id</th>
                <th>Name</th>
                <th>Father Name</th>
                <th>CNIC</th>
                <th>Mobile #</th>
                <th>District</th>
                <th>Action</th>


            </tr>
        </thead>
        <thead>
            <tr>
                <th><input type="text" data-column="0" class="search-input-text"></th>
                <th><input type="text" data-column="1" class="search-input-text"></th>
                <th><input type="text" data-column="2" class="search-input-text"></th>
                <th><input type="text" data-column="3" class="search-input-text"></th>
                <th><input type="text" data-column="4" class="search-input-text"></th>
                <th><input type="text" data-column="5" class="search-input-text"></th>
                <th></th>
            </tr>
        </thead>
        <tbody></tbody>

    </table>
</div>

<div class="modal modal-cust" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Are you sure?</h5>
                <button type="button" class="close no-btn" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="msg-body">
                <div class="modal-body">
                    <p class="popup-text"></p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary yes-btn">Yes</button>
                    <button type="button" class="btn btn-secondary no-btn" data-dismiss="modal">No</button>
                </div>
            </div>
            
            <div class="popup-msg-container">
                <div id="popup-msg" class="success">

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary no-btn" data-dismiss="modal">Close</button>
                </div>
            </div>
            
        </div>
    </div>
</div>

<script>
    $(function () {
        $("#btnSubmit").click(function () {
            $("input[name='GridHtml']").val($("#Grid").html());
        });


        $.loadBlockUserListings();
        var liId = "0";
        var stateId = "0";
        $(document).ajaxStart(function () {
            $("#Loading").fadeIn();
        });

        $(document).ajaxStop(function () {
            $("#Loading").fadeOut();
        });
        $("#agentListing").on("click", ".active-inactive", function (e) {
            //$(".active-inactive").click(function (e) {
            e.preventDefault();
                
             liId = $(this).attr('data-url');
             stateId = $(this).attr('state');
             $(".popup-msg-container").fadeOut();
             $(".msg-body").fadeIn();
             $(".modal-cust").fadeIn();
             if (stateId == "1") {
                 $(".popup-text").html("Inactive selected user with Id=" + liId);
             }
             else {
                 $(".popup-text").html("Active selected user with Id=" + liId);
             }
            //activeinactive(li_id, state);
        });
        $('.yes-btn').click(function (e) {

            activeinactive(liId, stateId);
        });
        $('.no-btn').click( function (e) {

            $(".modal-cust").fadeOut();
        });

    });

    $('.search-input-text').on('keyup', function (e) {

        e.preventDefault();
        var i = $(this).attr('data-column');
        var v = $(this).val();
        $('#agentListing').DataTable().columns(i).search(v).draw();
    });

    function activeinactive(li_id, state) {
        var url = "@Url.Action("SetUserActiveState", "AdminStakeholder")";
        var token = $('input[name="__RequestVerificationToken"]').val();
        $.ajax({
            url: url,
            type: "POST",
            data: { userId: li_id, isActive: state, __RequestVerificationToken: token },
            success: function (obj) {

                if (obj != null) {
                    
                    if (obj.statusId == 1) {

                        $("#popup-msg").html(obj.messageText);
                        $("#popup-msg").removeAttr("class");
                        $("#popup-msg").addClass(obj.css_cls);

                        $(".msg-body").fadeOut();
                        $(".popup-msg-container").fadeIn();

                        $.loadBlockUserListings();
                    }
                    else if (obj.statusId == 0) {
                        document.location.replace("@Url.Action("Login", "Account")");
                    }
                    else {
                        $("#popup-msg").html(obj.messageText);
                        $("#popup-msg").removeAttr("class");
                        $("#popup-msg").addClass(obj.css_cls);

                        $(".msg-body").fadeOut();
                        $(".popup-msg-container").fadeIn();
                    }
                }
                else {
                    
                }
            }

        });
    }

    $.loadBlockUserListings = function () {


        var table = $('#agentListing').dataTable({
            "dom": '<"top"<"col-md-6"l><"col-md-6"f><"col-md-6"i><"col-md-6"p>>',
            //fnInitComplete: function (oSettings, json) {
            //    counter = 1;
            //},
            "bDestroy": true,
            "iDisplayLength": 50,
            "processing": true,
            "responsive": true,
            "serverSide": true,
            "fnServerData": function (sSource, aoData, fnCallback) {
                var data = {};
                data.aoData = JSON.stringify(aoData);
               
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": '@Url.Action("GetBlockList", "AdminStakeholder")',//'../GeneralApi/GetStakeholderComplaintsServerSide',
                    "data": data,
                    "success": function (msg) {
                        //msg = JSON.parse(msg);
                        fnCallback(msg.Data);

                    },
                });
            },
            "columns": [
                       { "data": "Person_id" },
                       { "data": "Person_Name" },
                       { "data": "Person_Father_Name" },
                       { "data": "Cnic_No" },
                       { "data": "Mobile_No" },
                       { "data": "District_Name" }//,
                      // { "data": "ComplaintNo" }

            ],
            aoColumnDefs: [{
                "aTargets": [6],
                "bSearchable": false,
                "bSortable": false,
                "fnCreatedCell": function (nTd, sData, oData, iRow, iCol) {
                    $(nTd).css('text-align', 'center');
                },
                "mData": null,
                "mRender": function (data, type, full) {

                    if (full.Is_Active == true) {
                        return '<td style="text-align:center"><a data-original-title="View details" data-toggle="tooltip" href="#" class="active-inactive" state="1"  data-url="' + full.Person_id + '"><span class="fa fa-eye"></span> Inactive  </a></td>';
                    }
                    else {
                        return '<td style="text-align:center"><a data-original-title="View details" data-toggle="tooltip" href="#" class="active-inactive" state="0"  data-url="' + full.Person_id + '"><span class="fa fa-eye"></span> Active </a></td>';
                    }


                }
                }],


            });


    }
</script>