PITB.CMS/Controllers/View/ExecutiveCampaigns/ExecutiveCampaignsController.cs
using PITB.CMS_Common.Handler.Business;
using PITB.CMS_Common.Models.View.Executive;
using PITB.CMS_Common.Handler.Authorization;
using System;
using System.Web.Mvc;
using PITB.CMS_Common.Handler.Authentication;
using PITB.CMS_Common.Models.Custom.CustomForm;
using PITB.CMS_Common.Helper.Extensions;
using System.Globalization;
using PITB.CMS_Common.Models.Custom;
using PITB.CMS_Common.Models;
using PITB.CMS_Common;
using System.Dynamic;

namespace PITB.CMS.Controllers.View.ExecutiveCampaign
{
    public class ExecutiveCampaignsController : PITB.CMS_Common.Controllers.View.Controller
    {
        // GET: ExecutiveCampaign
        public ActionResult Index()
        {
            return View();
        }

        //[System.Web.Mvc.HttpPost]
        //public ActionResult OnStatsLinkClick(FormCollection fc)
        //{
        //    CustomForm.Post postedForm = new CustomForm.Post(Request);

        //    //dynamic d = new ExpandoObject();
        //    //idict
        //    ViewBag.data = new
        //    {
        //        tagId = postedForm.GetElementValue("tagId"),
        //        startDate = postedForm.GetElementValue("startDate"),
        //        endDate = postedForm.GetElementValue("endDate")
        //    }.ToExpando();
        //    ViewBag.data.logoUrl = "";
        //    ViewBag.data.pageHeading = "Munna kaka";
        //    //ViewBag.data = BlExecutive.PopulateListingTable(new
        //    //{
        //    //    tagId = postedForm.GetElementValue("itemId"),
        //    //    startDate = postedForm.GetElementValue("startDate"),
        //    //    endDate = postedForm.GetElementValue("endDate")
        //    //}.ToExpando());
        //    //return PartialView("~/Views/Stakeholder/Police/_PoliceComplaintListing.cshtml");
        //    //ViewEngineResult result = ViewEngines.Engines.FindView(this.ControllerContext, "~/Views/Stakeholder/Police/_PoliceComplaintListing.cshtml", null);
        //    //ViewEngineResult result2 = ViewEngines.Engines.FindView(this.ControllerContext, "~/Views/Shared/Partial/Table/_TableLayout.cshtml", null);
        //    //return View("~/Views/Stakeholder/Police/_PoliceComplaintListing.cshtml");
        //    dynamic d = new {
        //        tagId = postedForm.GetElementValue("tagId"),
        //        startDate = postedForm.GetElementValue("startDate"),
        //        endDate = postedForm.GetElementValue("endDate")
        //    }.ToExpando();
        //    dynamic data = BlExecutive.GetListingView(d);
        //    ViewBag.data = data.viewBag;
        //    return View(data.viewName);

        //    //return View("~/Views/Shared/Partial/Table/_TableLayout.cshtml");

        //    //HttpFileCollectionBase files = Request.Files;
        //    //NameValueCollection formCollection = Request.Form;


        //    //Config.CommandMessage commandMessage = null;
        //    //ControllerModel.Response resp = new ControllerModel.Response();
        //    //try
        //    //{
        //    //    CustomForm.Post postForm = new CustomForm.Post(Request);
        //    //    CMSCookie cmsCookie = AuthenticationHandler.GetCookie();
        //    //    PoliceModel.AddFeedback addFeedbackModel = new PoliceModel.AddFeedback(cmsCookie, postForm, DateTime.Now, Config.SourceType.Web/*, Config.OtherSystemId.Police*/, postForm.DictQueryParams["complaintId"]);
        //    //    commandMessage = BlPolice.SubmitComplaintFeedback(addFeedbackModel/*new CustomForm.Post(Request)*/);
        //    //    resp.RedirectUrl = Url.Action("AgentComplaintListingAllServerSide", "Complaint");
        //    //    resp.AddMessagePartialView(this, resp.ListPartialViewToLoadAfterRedirect, commandMessage);
        //    //}
        //    //catch (Exception ex)
        //    //{
        //    //    resp.AddMessagePartialView(this, resp.ListPartialView, Config.CommandMessage.GetFailureMessage());
        //    //}
        //    //return Json(resp);
        //}


        public ActionResult Dashboard()
        {
            ViewBag.StartDate = DateTime.Now.AddMonths(-3).ToString("yyyy-MM-dd");
            ViewBag.EndDate = DateTime.Now.ToString("yyyy-MM-dd");
            //ViewResult myView = View("~/Views/ExecutiveView/Dashboard.cshtml");
            //myView.MasterName = AuthenticationHandler.GetCookie().MasterPage;
            //return myView;


            CMSCookie cmsCookie = AuthenticationHandler.GetCookie();
            if (cmsCookie == null)
                return RedirectToAction("Login", "Account");
            else if (cmsCookie.navigationalData != null)
            {
                if (cmsCookie.navigationalData.StartDate != null)
                {
                    ViewBag.StartDate = cmsCookie.navigationalData.StartDate;
                    ViewBag.EndDate = cmsCookie.navigationalData.EndDate;
                }
            }
            if (cmsCookie.Role == CMS_Common.Config.Roles.ExecutiveCampaigns)
            {
                var page = AuthenticationHandler.GetCookie().MasterPage;
                return View("~/Views/ExecutiveCampaigns/Dashboard.cshtml", page);
            }
            else
            {


                //DbUsers dbUser = DbUsers.GetActiveUser(cmsCookie.PreviousLoginId);/*31735*/;
                //CMSCookie navigateCookie = CMSCookie.DbUserToCookie(dbUser);
                //cmsCookie = CMSCookie.DbUserToCookie(dbUser);
                //cmsCookie.UrlConfig = null;
                BlView.Instance.UpdateUserLogin(cmsCookie.UserId, cmsCookie, CMSCookie.DbUserToCookie(DbUsers.GetActiveUser((int)cmsCookie.PreviousLoginId)));
                return RedirectToAction("Login", "Account");
            }
            //return View("~/Views/ExecutiveCampaigns/Dashboard.cshtml", AuthenticationHandler.GetCookie().MasterPage);
        }



        [HttpGet]
        [OutputCache(Duration = 5, VaryByParam = "*")]
        public JsonResult GetCampaignDataById(int campaignId, string startDate, string endDate)
        {
            VmCampaignStatusWise response = BlExecutiveCampaigns.GetCompliantsDataBySingleCampaignId(campaignId, Convert.ToDateTime(startDate), Convert.ToDateTime(endDate));
            return Json(response, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        [OutputCache(Duration = 5, VaryByParam = "*")]
        public ActionResult ExecutiveCampaignView(string startDate, string endDate)
        {
            DateTime d1 = new DateTime();
            DateTime d2 = new DateTime();
            if (DateTime.TryParseExact(startDate, "dd/MM/yyyy h:mm:ss tt", System.Globalization.CultureInfo.CurrentCulture, System.Globalization.DateTimeStyles.None, out d1)
                || DateTime.TryParseExact(startDate, "MM/dd/yyyy h:mm:ss tt", System.Globalization.CultureInfo.CurrentCulture, System.Globalization.DateTimeStyles.None, out d1))
            {
                startDate = d1.ToString("yyyy-MM-dd");
            }
            if (DateTime.TryParseExact(startDate, "dd/MM/yyyy h:mm:ss tt", System.Globalization.CultureInfo.CurrentCulture, System.Globalization.DateTimeStyles.None, out d2)
                || DateTime.TryParseExact(startDate, "MM/dd/yyyy h:mm:ss tt", System.Globalization.CultureInfo.CurrentCulture, System.Globalization.DateTimeStyles.None, out d2))
            {
                endDate = d2.ToString("yyyy-MM-dd");
            }

            CMSCookie cmsCookie = AuthenticationHandler.GetCookie();
            cmsCookie.navigationalData = new ExpandoObject();
            cmsCookie.navigationalData.StartDate = startDate;
            cmsCookie.navigationalData.EndDate = endDate;
            new AuthenticationHandler().SaveCookie(cmsCookie);
            string templatePath = Server.MapPath(@"~/GeoData/PLRA.xml");
            //string errorFilePath = Server.MapPath(@"~/Exception.txt");
            //string RepsponsePath = Server.MapPath(@"~/Response.txt");
            //BlExecutiveCampaigns.filepath = templatePath;
            //BlExecutiveCampaigns.ErrorFilePath = errorFilePath;
            //BlExecutiveCampaigns.ReponsePath = RepsponsePath;
            //DateTime startDt = DateTime.ParseExact(startDate, "dd/MM/yyyy", CultureInfo.InvariantCulture);
            //DateTime endDt = DateTime.ParseExact(endDate, "dd/MM/yyyy", CultureInfo.InvariantCulture);
            //string asd = CMS_Common.Utility.GetSQLDateTimeFormat(startDt);
            VmDashboard dashboard = BlExecutiveCampaigns.GetDashboardModel(startDate, endDate);
            return PartialView("~/Views/ExecutiveCampaigns/_ExecutiveCampaignView.cshtml", dashboard);
        }

        public ActionResult GetPLRAComplaintDetails()
        {
            ViewBag.From = DateTime.Now.AddMonths(-12).ToString("yyyy-MM-dd");
            ViewBag.To = DateTime.Now.ToString("yyyy-MM-dd");
            return View("~/Views/Stakeholder/PLRA/_PLRAComplaintDetails.cshtml", BlView.Instance.GetMasterPageFromCookie());
        }
    }
}

PITB.CMS/Views/ExecutiveCampaigns/Dashboard.cshtml
@{
    ViewBag.Title = "Dashboard";
    //Layout = ViewBag.Layout;
}
<style>
    .form-padding {
        padding: 25px 15px;
        border-radius: 4px;
    }

    .btn-load {
        font-size: 14px;
        margin-top: 22px;
        padding: 6px 25px;
    }

        .btn-load span {
            margin-right: 10px;
            font-size: 12px;
        }

    .content-wrapper {
        min-height: 20px !important;
    }

    #datepicker > span:hover {
        cursor: pointer;
    }

    .fontCalendar span {
        position: absolute;
        /*left: 0;*/
        /*color: black;*/
        right: 20px;
        z-index: 9;
        background-color: transparent;
        top: 3;
    }

    .fontCalendar input {
        padding-left: 20px;
        background-color: white !important;
        border-radius: 20px !important;
    }

    .fontCalendar {
        width: 100%;
    }

    .input-group-addon {
        padding: 6px 8px;
        color: #1e672c !important;
        background-color: transparent !important;
        border: none !important;
        border-left: 1px solid #c3c3c3 !important;
    }

    .lable-text {
        color: #1e672c;
        padding-left: 19px;
    }

    .btn-load, .btn-load:active, .btn-load:focus {
        background-color: #2d63cb;
        border-color: #2d63cb;
    }

        .btn-load:hover {
            background-color: #2250a7;
            border-color: #2250a7;
        }
</style>
<div class="container-fluid">
    <div class="row margin-bottom">
        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
            @*<span class="lable-text">From Date</span>
                    <div id="datepickerFrom" class="input-group date fontCalendar">
                        <input id="StartDate" class="form-control" type="text" readonly value="@ViewBag.StartDate" />
                        <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
                    </div>

                </div>
                <div class="col-md-4">
                    <span class="lable-text">To Date</span>
                    <div id="datepickerTo" class="input-group date fontCalendar">
                        <input id="EndDate" class="form-control" type="text" readonly value="@ViewBag.EndDate" />
                        <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
                    </div>*@
            <span class="lable-text">Select Date</span>
            <div class="input-group date fontCalendar">
                <input type="text" id="dateRange" placeholder="" class="form-control" />
                <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
            </div>
        </div>
        <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12">
            <button type="button" value="Load" onclick="LoadData()" class="btn btn-success btn-sm btn-load"><i id="loadIcon" class="fa fa-refresh fa-fw"></i> Load</button>
        </div>
    </div>

    <div id="CampaignList">
        @{Html.RenderAction("ExecutiveCampaignView", "ExecutiveCampaigns", new { startDate = ViewBag.StartDate, endDate = ViewBag.EndDate });}
    </div>

</div>
<script type="text/javascript">
    $(document).ready(function () {
        $('#dateRange').daterangepicker({
            startDate: '@ViewBag.StartDate',
            endDate: '@ViewBag.EndDate',
            maxDate: '@(DateTime.Now.ToString("yyyy-MM-dd"))',
            showDropdowns: true,
            locale: {
                format: 'YYYY-MM-DD',
                separator: ' To ',
            }
        });
        $('#dateRange').on('apply.daterangepicker', function (ev, picker) {
            LoadData();
        });
    })
    //$(function () {
    //    $("#datepickerFrom").datepicker({
    //        format: 'yyyy-mm-dd',
    //        autoclose: true,
    //        todayHighlight: true,
    //    });
    //    $("#datepickerTo").datepicker({
    //        format: 'yyyy-mm-dd',
    //        autoclose: true,
    //        todayHighlight: true
    //    });
    //    $("#datepickerFrom").on("dp.change", function (e) {
    //        $('#datepickerTo').data("DateTimePicker").minDate(e.date);
    //    });
    //    $("#datepickerTo").on("dp.change", function (e) {
    //        $('#datepickerFrom').data("DateTimePicker").maxDate(e.date);
    //    });
    //})
    function LoadData() {
        debugger;
        $('#loadIcon').addClass('fa-spin');
        var startDate = $('#dateRange').val().split('To')[0].trim();
        var endDate = $('#dateRange').val().split('To')[1].trim();
        var url = '/ExecutiveCampaigns/ExecutiveCampaignView';
        $.ajax({
            async: false,
            contentType: 'application/x-www-form-urlencoded',
            type: 'GET',
            dataType: 'html',
            data: { startDate: startDate, endDate: endDate },
            url: url,
            success: function (result, status, xhr) {
                debugger;
                $("#CampaignList").empty();
                $("#CampaignList").html(result);
            },
            error: function (xhr, status, error) {
                debugger;
                alert(error);
            }
        });
        $('#loadIcon').removeClass('fa-spin');
    }
    function getHTML(url, callback) {
        debugger;
        if (!window.XMLHttpRequest)
            return;

        var xhr = new XMLHttpRequest();

        xhr.onload = function () {
            if (callback && typeof (callback) === 'function') {
                callback(this.responseXML);
            }
        }

        xhr.open('GET', url);
        xhr.responseType = 'document';
        xhr.send();
    }
    function getData(id) {
        debugger;
        var CampaignId = id;
        var startDate = $('#dateRange').val().split('To')[0].trim();
        var endDate = $('#dateRange').val().split('To')[1].trim();
        var url = '/ExecutiveCampaigns/GetCampaignDataById';
        $.ajax({
            async: false,
            contentType: 'application/x-www-form-urlencoded',
            type: 'GET',
            dataType: 'json',
            data: { campaignId: CampaignId, startDate: startDate, endDate: endDate },
            url: url,
            success: function (result, status, xhr) {
                debugger;
                var campId = result.CampaignId;
                for (i = 0; i < result.Status.length; i++) {
                    var obj = result.Status[i];
                    var count = result.Status[i].StatusCount;
                    var s = '#statusCount_' + campId + '_' + result.Status[i].StatusId;
                    //var doc = document.getElementById(s).innerHTML;
                    var elem = document.getElementById(s);
                    if (typeof elem !== 'undefined' && elem !== null) {
                        document.getElementById(s).innerHTML = count;
                    }
                    var d;
                }
                debugger;
                var e = 1;

            },
            error: function (xhr, status, error) {
                debugger;
                alert(error);
            }
        });
    }
</script>

PITB.CMS/Views/ExecutiveCampaigns/_ExecutiveCampaignView.cshtml
@model PITB.CMS_Common.Models.View.Executive.VmDashboard
@using Amazon.EC2
@using PITB.CMS_Common.Models.View.Executive;
@{
    int i = 0;
    int col = 3;
    int enddiv = 0;
}
<link href="~/css/newCards.css" rel="stylesheet" />
@foreach (VmCampaignWiseData item in Model.Campaignlst)
{
    if (i % col == 0)
    {
        @Html.Raw("<div class='row'>");
        enddiv = enddiv + (col - 1);
    }
    Html.RenderPartial("~/Views/ExecutiveCampaigns/_CampaignCard.cshtml", item);

    if (i == enddiv || i == Model.Campaignlst.Count)
    {
        @Html.Raw("</div>");
    }
    i++;
}