PITB.CMS/Models/View/Wasa/Stakeholder/VmWasaStakeholderComplaintListing.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PITB.CMS.Models.View.Wasa.Stakeholder
{
    public class VmWasaStakeholderComplaintListing : VmStakeholderComplaintListing
    {

        public string Complaint_SubCategory_Name { get; set; }

        public string Person_Contact { get; set; }

        public string Person_Address { get; set; }

        private string _complaint_Computed_Status;

        public string Computed_Time_Passed_Since_Complaint_Launch { get; set; }

        public override string Complaint_Computed_Status
        {
            get
            {
                if (_complaint_Computed_Status == Config.PendingFreshStatus)
                {
                    _complaint_Computed_Status = Config.WasaPendingFreshStatus;

                }
                return _complaint_Computed_Status;
            }
            set
            {
                _complaint_Computed_Status = value;
            }
        }


    }
}

PITB.CMS/Controllers/API/ZimmedarShehri/ApiZimmedarShehriController.cs
using PITB.CMS_Common.Handler.Business;
using PITB.CMS_Common.Models.Custom.Reports;
using System.Collections.Generic;
using System.Web.Http;
using System.Web.Mvc;

namespace PITB.CMS.Controllers.API.ZimmedarShehri
{
    public class ApiZimmedarShehriController : Controller
    {
        // GET: APIZimmedarShehri
        [System.Web.Mvc.HttpPost]
        public JsonResult RegionAndStatusWiseCountSummaryDistrict([FromBody] string startDate, [FromBody] string endDate, [FromBody] int provinceid,[FromBody] string campId, [FromBody] int hierarchyId,
           [FromBody] int userHierarchyId, [FromBody] string commaSepVal, [FromBody] string statusIds, [FromBody] int reportType, [FromBody] string divTag)
        {

            List<MainSummaryReport.ZimmedarShehriRegionAndStatusWiseCount> listRegionWiseCountList = BlZimmedarShehri.RegionAndStatusWiseCountReportDistrict(startDate, endDate, provinceid,
                campId, hierarchyId, userHierarchyId, commaSepVal, statusIds, reportType);
            return Json(new
            {
                data = listRegionWiseCountList
            }, JsonRequestBehavior.AllowGet);

            return null;
        }

        [System.Web.Mvc.HttpPost]
        public JsonResult RegionAndStatusWiseCountSummaryDivision([FromBody] string startDate, [FromBody] string endDate, [FromBody] int provinceid, [FromBody] string campId, [FromBody] int hierarchyId,
            [FromBody] int userHierarchyId, [FromBody] string commaSepVal, [FromBody] string statusIds, [FromBody] int reportType, [FromBody] string divTag)
        {

            List<MainSummaryReport.ZimmedarShehriRegionAndStatusWiseCount> listRegionWiseCountList = BlZimmedarShehri.RegionAndStatusWiseCountReportDivision(startDate, endDate, provinceid,
                campId, hierarchyId, userHierarchyId, commaSepVal, statusIds, reportType);
            return Json(new
            {
                data = listRegionWiseCountList
            }, JsonRequestBehavior.AllowGet);

            return null;
        }

        [System.Web.Mvc.HttpPost]
        public ActionResult RegionStatusWiseCountSummaryTehsil([FromBody] string startDate, [FromBody] string endDate, [FromBody] int districtId, [FromBody] int campaignId,
            [FromBody] int hierarchyId, [FromBody] int userHierarchyId, [FromBody] string commaSepVal,[FromBody] string statusIds,[FromBody] int divTag)            
        {
            List<MainSummaryReport.ZimmedarShehriRegionAndStatusWiseCount> listRegionWiseCountList = BlZimmedarShehri.RegionAndStatusWiseCountReportTehsil(startDate, endDate, districtId,
         campaignId, hierarchyId, userHierarchyId, commaSepVal, statusIds);
            return Json(new
            {
                data = listRegionWiseCountList
            }, JsonRequestBehavior.AllowGet);

            return null;
        }
        [System.Web.Mvc.HttpPost]
        public ActionResult RegionWiseFeedbackReport([FromBody] string startDate, [FromBody] string endDate, [FromBody] int hierarchyId, [FromBody] int provinceId, [FromBody] int campaignId,[FromBody] int upperHierarchyId)
        {
            List<RegionWiseFeedback> lstRegionWiseFeedback = BlZimmedarShehri.RegionWiseFeedbackReport(startDate, endDate, hierarchyId, campaignId, provinceId,upperHierarchyId);
            return Json(new
            {
                data = lstRegionWiseFeedback
            }, JsonRequestBehavior.AllowGet);

        }
    }
}

PITB.CMS/Controllers/View/StakeholderController.cs
using PITB.CMS_Common.Handler.Business;
using PITB.CMS_Common.Models.View;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PITB.CMS_Common.Handler.Authorization;
//using PITB.CMS.Handler.Authorization;
//using PITB.CMS.Handler.Business;
//using PITB.CMS.Models.View;

namespace PITB.CMS.Controllers.View
{
    [AuthorizePermission]
    public class StakeholderController : Controller
    {
        // GET: Stakeholder
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetResolverDetail(int userId)
        {
            //VmComplaintDetail vmComplaintDetail = BlComplaints.GetComplaintDetail(complaintId);
            VmResolverDetail vmResolverDetail = BlUsers.GetResolverDetail(userId);
            return PartialView("_ResolverDetail", vmResolverDetail);
        }
    }
}

PITB.CMS/Controllers/View/ZimmedarShehri/ZimmedarShehriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Text.RegularExpressions;
using PITB.CMS_Common.Models.View;
using PITB.CMS_Common.Handler.Business;
using PITB.CMS_Common;
using PITB.CMS_Common.Models;
using PITB.CMS_Common.Handler.Authentication;
using PITB.CMS_Common.Models.Custom;
using PITB.CMS_Common.Handler.Permission;
using PITB.CMS_Common.Handler.FileUpload;
using PITB.CMS_Common.Handler.Authorization;

namespace PITB.CMS.Controllers.View.ZimmedarShehri
{
    [AuthorizePermission]
    public class ZimmedarShehriController : PITB.CMS_Common.Controllers.View.Controller
    {
        // GET: ZimmedarShehri
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult StakeholderDetail(int complaintId, VmStakeholderComplaintDetail.DetailType detailType)
        {
            CMSCookie cookie = AuthenticationHandler.GetCookie();
            VmStakeholderComplaintDetail vmComplaintDetail = BlComplaints.GetStakeholderComplaintDetail(complaintId, cookie.UserId, detailType);
            return PartialView("~/Views/Stakeholder/ZimmedarShehri/ZimmedarShehriDetail.cshtml", vmComplaintDetail);
        }

        [System.Web.Mvc.HttpPost]
        public ActionResult OnStatusChange(VmStatusChange vmStatusChange, IEnumerable<HttpPostedFileBase> files)
        {
            if (ModelState.IsValid)
            {
                FileUploadHandler.FileValidationStatus validationStatus = BlZimmedarShehri.ChangeStatus(vmStatusChange, System.Web.HttpContext.Current.Request.Files);
                if (validationStatus.ValidationStatus == Config.AttachmentErrorType.NoError)
                {
                    TempData["Message"] = StatusMessage(Config.CommandStatus.Success, validationStatus.ValidationMessage,
                        Config.Message.UpdateSuccess, Config.Message.Error);
                }
                else
                {
                    TempData["Message"] = StatusMessage(Config.CommandStatus.Failure, "",
                        validationStatus.ValidationMessage, Config.Message.Error);
                }
                //TempData["Message"] = StatusMessage(Config.CommandStatus.Success, "Complaint " + vmStakeholderComplaint.Compaign_Id+"-"+vmStakeholderComplaint.ComplaintId + " status changed successfully!! ", Config.Message.UpdateSuccess, Config.Message.Error);


                //var status = vmStakeholderComplaint.AddComplaint(complaintModel, (complaintModel.PersonalInfoVm.Person_id > 0),
                //     (complaintModel.ComplaintVm.Id != 0));
                //TempData["Message"] = StatusMessage(status.Status, "Complaint added successfully , your complaint number : " + status.Value, Config.Message.Failure, Config.Message.Error);
                //return RedirectToAction("Search");

            }
            /*
            string actionName = this.ControllerContext.RouteData.Values["action"].ToString();
            string controllerName = this.ControllerContext.RouteData.Values["controller"].ToString();
            return RedirectToAction("controllerName", "actionName");
            */

            //return StakeholderComplaintsListingServerSide();
            return RedirectToAction("StakeholderComplaintsListingServerSide", "Complaint");


            //ViewBag.Ddl = UtilityExtensions.GetDummySelectList();
            //VmAddComplaint vmodel = BlComplaints.GetVmAddComplaintMerged(new VmAddComplaint(), (int)complaintModel.PersonalInfoVm.Person_id,
            //     (int)complaintModel.ComplaintVm.Compaign_Id);

            //ViewBag.Campaignname = DbCampaign.GetById((int)complaintModel.ComplaintVm.Compaign_Id).LogoUrl;
            //return View("Add", vmodel);
            //return null;
            //return RedirectToAction("StakeholderComplaints");
            //return Json(true);
        }

        public ActionResult UserWiseComplaintsMain(string campaignId)
        {
            DbCampaign dbCamp = DbCampaign.GetById(Convert.ToInt32(campaignId));

            CMSCookie cmsCookie = AuthenticationHandler.GetCookie();
            ViewBag.CampaignName = BlView.GetAlteredCampaignName(cmsCookie, dbCamp.Campaign_Name);
            //if (cmsCookie.navigationalData != null && cmsCookie.navigationalData.campaignName != null)
            //    ViewBag.CampaignName = cmsCookie.navigationalData.campaignName;
            //else
            //    ViewBag.CampaignName = dbCamp.Campaign_Name;

            ViewBag.LogoUrl = dbCamp.LogoUrl;
            ViewBag.CampignIds = campaignId;
            // user cookie
            //VmStatusWiseComplaintsData statusWiseData = BlSchool.GetUsersDashboardData(new AuthenticationHandler().CmsCookie.UserId, "2016-01-01", "2018-01-01", Config.UserWiseGraphType.CumulationOfLower);
            // end user cookie
            return View("~/Views/Stakeholder/ZimmedarShehri/UserWiseReportMain.cshtml", BlView.Instance.GetMasterPageFromCookie());


            /*

            DbUsers dbUsers = Utility.GetUserFromCookie();
            ViewBag.CampaignIds = campaignId;
            ViewBag.ProvinceName = Utility.GetHierarchyValue(Config.Hierarchy.Province, (int)dbUsers.Hierarchy_Id);
            if (dbUsers.Hierarchy_Id == Config.Hierarchy.District)
            {
                List<DbDistrict> listDbDistrict = new List<DbDistrict>();
                listDbDistrict.Add(DbDistrict.GetById(Convert.ToInt32(dbUsers.District_Id)));
                ViewBag.DistrictList = listDbDistrict.ToSelectList("District_Id", "District_Name");
                ViewBag.TehsilList = new List<SelectListItem>();
            }
            
            return View("~/Views/Stakeholder/ZimmedarShehri/UserWiseReportMain.cshtml");
            */
        }
        public ActionResult RegionAndStatusWiseCountSummaryDistrict(string divName, string startDate, string endDate, string provinceid, string campId, int hierarchyId, int userHierarchyId, string commaSepVal, string statusIds, int reportType, string divTag)
        {
            ViewBag.divName = divName;
            ViewBag.divNameTrimmed = Regex.Replace(divName, @"[^0-9a-zA-Z]+", "").Replace(" ", "").Trim();
            ViewBag.startDate = startDate;
            ViewBag.endDate = endDate;
            ViewBag.campId = campId;
            ViewBag.hierarchyId = hierarchyId;
            ViewBag.userHierarchyId = userHierarchyId;
            ViewBag.provinceid = Int32.Parse(provinceid);
            ViewBag.commaSepVal = commaSepVal;
            ViewBag.statusIds = statusIds;
            ViewBag.reportType = reportType;
            ViewBag.divTag = divTag;
            ViewBag.Hierarchy1 = Config.RegionDict[hierarchyId];
            ViewBag.Hierarchy2 = Config.RegionDict[hierarchyId + 1];

            return PartialView("~/Views/Stakeholder/ZimmedarShehri/_RegionStatusWiseCountSummaryDistrict.cshtml");
        }
        public ActionResult RegionAndStatusWiseCountSummaryDivision(string divName, string startDate, string endDate, string provinceid, string campId, int hierarchyId, int userHierarchyId, string commaSepVal, string statusIds, int reportType, string divTag)
        {
            ViewBag.divName = divName;
            ViewBag.divNameTrimmed = Regex.Replace(divName, @"[^0-9a-zA-Z]+", "").Replace(" ", "").Trim();
            ViewBag.startDate = startDate;
            ViewBag.endDate = endDate;
            ViewBag.campId = campId;
            ViewBag.hierarchyId = hierarchyId;
            ViewBag.userHierarchyId = userHierarchyId;
            ViewBag.provinceid = Int32.Parse(provinceid);
            ViewBag.commaSepVal = commaSepVal;
            ViewBag.statusIds = statusIds;
            ViewBag.reportType = reportType;
            ViewBag.divTag = divTag;
            ViewBag.Hierarchy1 = Config.RegionDict[hierarchyId];
            ViewBag.Hierarchy2 = Config.RegionDict[hierarchyId + 1];

            return PartialView("~/Views/Stakeholder/ZimmedarShehri/_RegionStatusWiseCountSummaryDivision.cshtml");
        }
        public ActionResult RegionWiseFeedbackSummary(string startDate, string endDate, string provinceId, int campaignId, int hierarchyId, string divTag, int upperHierarchyId)
        {
            ViewBag.divTag = divTag;
            ViewBag.startDate = startDate;
            ViewBag.endDate = endDate;
            ViewBag.campaignId = campaignId;
            ViewBag.hierarchyId = hierarchyId;
            ViewBag.provinceId = Int32.Parse(provinceId);
            ViewBag.Hierarchy1 = Config.RegionDict[hierarchyId];
            ViewBag.UpperHierarchyId = upperHierarchyId;
            return PartialView("~/Views/Stakeholder/ZimmedarShehri/_RegionWiseFeedbackSummary.cshtml");
        }
        public ActionResult GetDistrictComplaintsData(int campaignId)
        {
            DbUsers dbUsers = Utility.GetUserFromCookie();
            DbCampaign dbCamp = DbCampaign.GetById(Convert.ToInt32(campaignId));
            ViewBag.LogoUrl = dbCamp.LogoUrl;
            ViewBag.CampaignName = dbCamp.Campaign_Name;
            ViewBag.CampignIds = campaignId;
            ViewBag.UserId = dbUsers.User_Id;
            ViewBag.provinceid = dbUsers.Province_Id;
            ViewBag.HierarchyId = 3;// Convert.ToInt32(dbUsers.Hierarchy_Id);
            ViewBag.UserHierarchyId = Convert.ToInt32(dbUsers.User_Hierarchy_Id);
            //ViewBag.commaSepVal = DbUsers.GetHierarchy((Config.Hierarchy)dbUsers.Hierarchy_Id, dbUsers);
            ViewBag.commaSepVal = DbDistrict.GetDistrictsByProvinceId(Convert.ToInt32(dbUsers.Province_Id));
            ViewBag.ReportType = Config.SummaryReportType.General;
            ViewBag.ProvinceName = Utility.GetHierarchyValueName(Config.Hierarchy.Province, Int32.Parse(dbUsers.Province_Id));
            BlView.Instance.SetStartEndDate(this);
            return View("~/Views/Stakeholder/ZimmedarShehri/GetDistrictComplaintsData.cshtml", BlView.Instance.GetMasterPageFromCookie());
        }

PITB.CMS/Views/Stakeholder/ZimmedarShehri/_RegionStatusWiseCountSummaryDistrict.cshtml
<div class="box-header-blue with-border btn-header">
    <h4 class="box-title"><img style="max-width:40px; max-height: 40px; margin-top: -3px; margin-right: 15px;">Complaints by @ViewBag.Hierarchy1</h4>
</div>

<div class="box-body-white">

    <table id="RegionStatusWiseTable_@(ViewBag.divTag)" width="100%" class="table table-condensed table-hover table-bordered table-striped  responsive" role="grid" aria-describedby="agentListing">
        <thead>
            <tr role="row" class="tableHeader">
                <th class="nosort">Sr No</th>
                <th>@ViewBag.Hierarchy1</th>
                <th>Overdue</th>
                <th>Pending (Fresh)</th>
                <th>Pending (Reopened)</th>
                <th>Irrelevant</th>
                <th>In-Progress</th>
                <th>Resolved</th>
                <th>Total</th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <th>
                </th>
                <th>
                    Total
                </th>
                <th>
                </th>
                <th>
                </th>
                <th>
                </th>
                <th>
                </th>
                <th>
                </th>
                <th>
                </th>
                <th>
                </th>
            </tr>
        </tfoot>
        <tbody></tbody>

    </table>
</div>



<style>
    th {
        font-size: 17px;
    }

    tr {
        font-size: 17px;
    }
</style>
<script type="text/javascript">
    $(function() {
        debugger;
        LoadData@(ViewBag.divTag)();

    });
    function LoadData@(ViewBag.divTag)()
        {
        LoadTable@(ViewBag.divTag)("@Url.Action("RegionAndStatusWiseCountSummaryDistrict", "ApiZimmedarShehri")");
        }
    function LoadTable@(ViewBag.divTag)(apiUrl, from, to, campaign, cateogries, statuses) {
        debugger;
        var table = $('#RegionStatusWiseTable_@(ViewBag.divTag)').dataTable({
            "dom": '<"top"<"col-md-6"l><"col-md-6"f><"col-md-6"i><"col-md-6"p>>',
            fnInitComplete: function (oSettings, json) {
                counter = 1;
            },
            drawCallback: function(row, data, start, end, display) {
                var api = this.api();
                debugger;
                data = api.column(2).data();
                var totalcount = data.length ? data.reduce(function(a,b){
                    var x = parseFloat(a) || 0;
                    var y = parseFloat(b) || 0;
                    return x + y;}):0;
                api.columns('.sum', { page: 'current' }).every(function () {
                    var sum = api
                        .cells( null, this.index(), { page: 'current'} )
                        .render('display')
                        .reduce(function (a, b) {
                            var x = parseFloat(a) || 0;
                            var y = parseFloat(b) || 0;
                            return x + y;
                        }, 0);
                    var val = sum*100/totalcount;

                    //$(this.footer()).html(sum +'  ('+ Math.floor(val) + '%)');
                    $(this.footer()).html(sum);
                });

            },
            "footerCallback": function () {
                debugger;
                //var api = this.api();

                //var table = api.table();
                //var closed =  0;
                //var reopened = 0;
                //var tab = table.column(6).data();
                //if (tab.length > 0 ){
                //    var x = table.column(6).data();
                //    for (i = 0; i < x.length; i++) {
                //        closed = closed + x[i];
                //    }
                //}
                //var tab2 = table.column(5).data();
                //if (tab2.length > 0 ){
                //    var x = table.column(5).data();
                //    for (i = 0; i < x.length; i++) {
                //        reopened = reopened + x[i];
                //    }

                //}



                ///// (api.column( 5, {page:'current'} ).data().sum() + api.column( 6, {page:'current'} ).data().sum());
                //////Sub Total
                //if (table !== undefined){
                //    if ((closed + reopened) > 0)
                //    {
                //        $(api.column(8).footer()).html(
                //            Math.round((closed / (closed + reopened))*100) + ' %'
                //        );
                //    }
                //}
            },
            "bDestroy": true,
            "iDisplayLength": 50,
            "processing": false,
            "responsive": true,
            "serverSide": false,
            "order" : [[2,"desc"]],
            'columnDefs': [{
                "targets": [ ], //first column / numbering column
                "orderable": true, //set not orderable
            }],
            "ajax": {
                "url": apiUrl,//'../GeneralApi/GetStakeholderComplaints',
                "type": "POST",
                data: {
                    startDate: $('#pieDateRange').val().split('To')[0].trim(),
                    endDate: $('#pieDateRange').val().split('To')[1].trim(),
                    provinceid: @((int)ViewBag.provinceid),
                    campId: @((string)ViewBag.campId),
                    hierarchyId: @((int)ViewBag.hierarchyId),
                    userHierarchyId: @((int)ViewBag.userHierarchyId),
                    commaSepVal: '@((string)ViewBag.commaSepVal)',
                    statusIds: '@(ViewBag.statusIds)',
                    reportType: @((int)ViewBag.reportType),
                    divTag: @((string)ViewBag.divTag),
                    }
                //data: { from: from, to: to, campaign: campaign, cateogries: cateogries, statuses: statuses }
            },
            "columns": [
                       { "data": "SrNo",
                           render: function (data, type, row, meta) {
                           return meta.row + meta.settings._iDisplayStart + 1;
                           },"bSortable": true
                       },
                       { "data": "Hierarchy1Data" },
                       { "data": "Overdue", className: "sum" },
                       { "data": "PendingFresh", className: "sum" },
                        { "data": "PendingReopened", className: "sum" },
                        { "data": "Irrelevant", className: "sum" },
                        {"data": "Forwarded",className:"sum"},
                       { "data": "Resolved" , className: "sum"},
                       { "data": "Total" , className: "sum"},
                       //{ "data": "PercentageClosed", className: "percentage" }
            ],
        });
        debugger;
        //table.on( 'order.dt search.dt', function () {
        //    table.column(0, {search:'applied', order:'applied'}).nodes().each( function (cell, i) {
        //        cell.innerHTML = i+1;
        //    } );
        //} ).draw();
        DivData.push(table);
    }
</script>

PITB.CMS/Views/Stakeholder/ZimmedarShehri/_TehsilByDistrictPartialView.cshtml
<div class="box-header-blue with-border btn-header">
    <h4 class="box-title"><img style="max-width:40px; max-height: 40px; margin-top: -3px; margin-right: 15px;">Complaints by @ViewBag.Hierarchy1</h4>
</div>

<div class="box-body-white">

    <table id="RegionStatusWiseTable_@(ViewBag.divTag)" width="100%" class="table table-condensed table-hover table-bordered table-striped  responsive" role="grid" aria-describedby="agentListing">
        <thead>
            <tr role="row" class="tableHeader">
                <th class="nosort">Sr No</th>
                <th>@ViewBag.Hierarchy1</th>
                <th>Overdue</th>
                <th>Pending (Fresh)</th>
                <th>Pending (Reopened)</th>
                <th>Irrelevant</th>
                <th>In-Progress</th>
                <th>Resolved</th>
                <th>Total</th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <th>
                </th>
                <th>
                    Total
                </th>
                <th>
                </th>
                <th>
                </th>
                <th>
                </th>
                <th>
                </th>
                <th>
                </th>
                <th>
                </th>
                <th>
                </th>
            </tr>
        </tfoot>
        <tbody></tbody>

    </table>
</div>

<div class="feedback">
    @{Html.RenderAction("RegionWiseFeedbackSummary", "ZimmedarShehri", new { divTag = "4", startDate = ViewBag.StartDate, endDate = ViewBag.EndDate, provinceid = ViewBag.ProvinceId, campaignId = ViewBag.CampaignId, hierarchyId = ViewBag.HierarchyId, upperHierarchyId = ViewBag.UpperHierarchyId });}
</div>

<style>
    th {
        font-size: 17px;
    }

    tr {
        font-size: 17px;
    }
</style>
<script type="text/javascript">
    $(function() {
        debugger;
        LoadData@(ViewBag.divTag)();

    });
    function LoadData@(ViewBag.divTag)()
        {
        LoadTable@(ViewBag.divTag)("@Url.Action("RegionStatusWiseCountSummaryTehsil", "ApiZimmedarShehri")");
        }
    function LoadTable@(ViewBag.divTag)(apiUrl, from, to, campaign, cateogries, statuses) {
        debugger;
        var table = $('#RegionStatusWiseTable_@(ViewBag.divTag)').dataTable({
            "dom": '<"top"<"col-md-6"l><"col-md-6"f><"col-md-6"i><"col-md-6"p>>',
            fnInitComplete: function (oSettings, json) {
                counter = 1;
            },
            drawCallback: function (row, data, start, end, display) {
                var api = this.api();
                debugger;
                data = api.column(2).data();
                var totalcount = data.length ? data.reduce(function (a, b) {
                    var x = parseFloat(a) || 0;
                    var y = parseFloat(b) || 0;
                    return x + y;
                }) : 0;
                api.columns('.sum', { page: 'current' }).every(function () {
                    var sum = api
                        .cells(null, this.index(), { page: 'current' })
                        .render('display')
                        .reduce(function (a, b) {
                            var x = parseFloat(a) || 0;
                            var y = parseFloat(b) || 0;
                            return x + y;
                        }, 0);
                    var val = sum * 100 / totalcount;
                    
                    //$(this.footer()).html(sum +'  ('+ Math.floor(val) + '%)');
                    $(this.footer()).html(sum);
                });

            },
            "footerCallback": function () {
                debugger;
                //var api = this.api();

                //var table = api.table();
                //var closed =  0;
                //var reopened = 0;
                //var tab = table.column(6).data();
                //if (tab.length > 0 ){
                //    var x = table.column(6).data();
                //    for (i = 0; i < x.length; i++) {
                //        closed = closed + x[i];
                //    }
                //}
                //var tab2 = table.column(5).data();
                //if (tab2.length > 0 ){
                //    var x = table.column(5).data();
                //    for (i = 0; i < x.length; i++) {
                //        reopened = reopened + x[i];
                //    }

                //}


                
                ///// (api.column( 5, {page:'current'} ).data().sum() + api.column( 6, {page:'current'} ).data().sum());
                //////Sub Total
                //if (table !== undefined){
                //    if ((closed + reopened) > 0)
                //    {
                //        $(api.column(8).footer()).html(
                //            Math.round((closed / (closed + reopened))*100) + ' %'
                //        );
                //    }
                //}
            },
            "bDestroy": true,
            "iDisplayLength": 50,
            "processing": false,
            "responsive": true,
            "serverSide": false,
            "order": [[2, "desc"]],
            'columnDefs': [{
                "targets": [], //first column / numbering column
                "orderable": true, //set not orderable
            }],
            "ajax": {
                "url": apiUrl,//'../GeneralApi/GetStakeholderComplaints',
                "type": "POST",
                data: {
                    startDate: $('#pieDateRange').val().split('To')[0].trim(),
                    endDate: $('#pieDateRange').val().split('To')[1].trim(),
                    districtId: @((int)ViewBag.DistrictId),
                    campaignId: @((int)ViewBag.CampaignId),
                    hierarchyId: @((int)ViewBag.HierarchyId),
                    userHierarchyId: @((int)ViewBag.UserHierarchyId),
                    commaSepVal: '@((string)ViewBag.CommaSepVal)',
                    statusIds: '@((string)ViewBag.StatusIds)',
                    divTag: @((int)ViewBag.divTag),
                }
                //data: { from: from, to: to, campaign: campaign, cateogries: cateogries, statuses: statuses }
            },
            "columns": [
                {
                    "data": "SrNo",
                    render: function (data, type, row, meta) {
                        return meta.row + meta.settings._iDisplayStart + 1;
                    }, "bSortable": true
                },
                { "data": "Hierarchy1Data" },
                { "data": "Overdue", className: "sum" },
                { "data": "PendingFresh", className: "sum" },
                { "data": "PendingReopened", className: "sum" },
                { "data": "Irrelevant", className: "sum" },
                { "data": "Forwarded", className: "sum" },
                { "data": "Resolved", className: "sum" },
                { "data": "Total", className: "sum" },
                //{ "data": "PercentageClosed", className: "percentage" }
            ],
        });
        debugger;
        //table.on( 'order.dt search.dt', function () {
        //    table.column(0, {search:'applied', order:'applied'}).nodes().each( function (cell, i) {
        //        cell.innerHTML = i+1;
        //    } );
        //} ).draw();
        DivData.push(table);
    }
</script>